### ISSUE TITLE
Bulk insert of triples

### ISSUE THREAD

**Issue by abargnesi** [mro/librdf.sqlite#10] opened 2015-10-23 20:48 UTC
First off, great work. It seems like a promising improvement over the stock SQLite storage.

I am creating a SQLite database of around 20 million triples and insert seems to slow as I am inserting.

I have set the `synchronous` option of `off` to disable journaling, but it doesn't seem to help much. With the stock SQLite storage it seems to insert at a consistent rate.

Are there additional options to speed up bulk-insert?

**Comment by abargnesi** [comment] 2015-10-23 21:13
Sorry it seems like I might have using the stock sqlite storage. I have replaced now replaced the stock implementation with your version and I'm getting consistent rates.

**Comment by mro** [comment] 2015-10-23 21:28
nice to hear. For curiosity's sake, could you post some numbers?

P.S.: for speedup: try explicitly `transaction_start ... transaction_commit` in case the memory doesn't blow up.

**Comment by abargnesi** [comment] 2015-10-24 02:43
My dataset contains 19799726 triples.

I tested the following query on the `triples` view:

```sql
select * from triples where p_uri = 'http://www.openbel.org/vocabulary/prefix';
```

The following results seem to indicate a full table scan of the `triple_relations` table:

```sql
sqlite> .explain
sqlite> .eqp on
sqlite> .timer on
sqlite> select * from triples where p_uri = 'http://www.openbel.org/vocabulary/prefix';
--EQP-- 0,0,0,SCAN TABLE triple_relations
--EQP-- 0,1,1,SEARCH TABLE so_uris AS s_uris USING INTEGER PRIMARY KEY (rowid=?)
--EQP-- 0,2,2,SEARCH TABLE so_blanks AS s_blanks USING INTEGER PRIMARY KEY (rowid=?)
--EQP-- 0,3,3,SEARCH TABLE p_uris AS p_uris USING INTEGER PRIMARY KEY (rowid=?)
--EQP-- 0,4,4,SEARCH TABLE so_uris AS o_uris USING INTEGER PRIMARY KEY (rowid=?)
--EQP-- 0,5,5,SEARCH TABLE so_blanks AS o_blanks USING INTEGER PRIMARY KEY (rowid=?)
--EQP-- 0,6,6,SEARCH TABLE o_literals AS o_literals USING INTEGER PRIMARY KEY (rowid=?)
--EQP-- 0,7,7,SEARCH TABLE t_uris AS o_lit_uris USING INTEGER PRIMARY KEY (rowid=?)
--EQP-- 0,8,8,SEARCH TABLE c_uris AS c_uris USING INTEGER PRIMARY KEY (rowid=?)
id    s_uri_id       s_bl  p_ur  o_ur  o_blank_id     o_  o_datatype_id  c_uri_id    s_uri                                               s_blank     p_uri                                     o_uri       o_blank     o_text      o_language  o_datatype                               c_uri     
----  -------------  ----  ----  ----  -------------  --  -------------  ----------  --------------------------------------------------  ----------  ----------------------------------------  ----------  ----------  ----------  ----------  ---------------------------------------  ----------
-8953203191115340872  -2153809890787916446        8891365258715654442                       -761117637572586306  -7210322708539680434              http://www.openbel.org/bel/namespace/rgd-rat-genes              http://www.openbel.org/vocabulary/prefix                          rgd                     http://www.w3.org/2001/XMLSchema#string            
-5942690236445784542  -5651519178411819840        8891365258715654442                       -120847399540968945  -7210322708539680434              http://www.openbel.org/bel/namespace/mesh-anatomy               http://www.openbel.org/vocabulary/prefix                          mesha                   http://www.w3.org/2001/XMLSchema#string            
-5750330924181196839  1625998193914647814        8891365258715654442                       3684776179048037764  -7210322708539680434              http://www.openbel.org/bel/namespace/swissprot                  http://www.openbel.org/vocabulary/prefix                          sp                      http://www.w3.org/2001/XMLSchema#string            
-5639833229778965523  -1834755243247703679        8891365258715654442                       -3777992359957531766  -7210322708539680434              http://www.openbel.org/bel/namespace/cell-line-ontology              http://www.openbel.org/vocabulary/prefix                          clo                     http://www.w3.org/2001/XMLSchema#string            
-5432515727605213476  -2024215230190190826        8891365258715654442                       7694073778182938261  -7210322708539680434              http://www.openbel.org/bel/namespace/mgi-mouse-genes              http://www.openbel.org/vocabulary/prefix                          mgi                     http://www.w3.org/2001/XMLSchema#string            
-4522727871672482014  6251866281173790839        8891365258715654442                       -227163063072304314  -7210322708539680434              http://www.openbel.org/bel/namespace/experimental-factor-ontology              http://www.openbel.org/vocabulary/prefix                          efo                     http://www.w3.org/2001/XMLSchema#string            
-3419368143309930828  6718338200768323000        8891365258715654442                       -1636581229217248134  -7210322708539680434              http://www.openbel.org/bel/namespace/cell-ontology              http://www.openbel.org/vocabulary/prefix                          cl                      http://www.w3.org/2001/XMLSchema#string            
-1757139288187511514  5908700977917003841        8891365258715654442                       6233310147803604084  -7210322708539680434              http://www.openbel.org/bel/namespace/ncbi-taxonomy              http://www.openbel.org/vocabulary/prefix                          taxon                   http://www.w3.org/2001/XMLSchema#string            
-1485986718452197738  6916964323530588694        8891365258715654442                       8012652466210525602  -7210322708539680434              http://www.openbel.org/bel/namespace/affy-probeset              http://www.openbel.org/vocabulary/prefix                          affx                    http://www.w3.org/2001/XMLSchema#string            
-1076062797968999171  1765045227617811608        8891365258715654442                       -8763427777865176605  -7210322708539680434              http://www.openbel.org/bel/namespace/mesh-diseases              http://www.openbel.org/vocabulary/prefix                          meshd                   http://www.w3.org/2001/XMLSchema#string            
-1027106250966710582  2665414293436938691        8891365258715654442                       -7539692296793019894  -7210322708539680434              http://www.openbel.org/bel/namespace/entrez-gene                http://www.openbel.org/vocabulary/prefix                          egid                    http://www.w3.org/2001/XMLSchema#string            
-242850415018138191  6076170973665239127        8891365258715654442                       -6762884962701503883  -7210322708539680434              http://www.openbel.org/bel/namespace/chebi                      http://www.openbel.org/vocabulary/prefix                          chebi                   http://www.w3.org/2001/XMLSchema#string            
2087263891606945741  -1967734694912135205        8891365258715654442                       8500928990870149547  -7210322708539680434              http://www.openbel.org/bel/namespace/go-biological-process              http://www.openbel.org/vocabulary/prefix                          gobp                    http://www.w3.org/2001/XMLSchema#string            
2404370976512930390  -4736273581141158102        8891365258715654442                       2799465496762415635  -7210322708539680434              http://www.openbel.org/bel/namespace/go-cellular-component              http://www.openbel.org/vocabulary/prefix                          gocc                    http://www.w3.org/2001/XMLSchema#string            
2545215817738855362  -5196219641959336837        8891365258715654442                       -1576279980644318209  -7210322708539680434              http://www.openbel.org/bel/namespace/mesh-processes              http://www.openbel.org/vocabulary/prefix                          meshpp                  http://www.w3.org/2001/XMLSchema#string            
4083383934576935379  3472155070150475385        8891365258715654442                       7897920779876238115  -7210322708539680434              http://www.openbel.org/bel/namespace/selventa-named-complexes              http://www.openbel.org/vocabulary/prefix                          scomp                   http://www.w3.org/2001/XMLSchema#string            
4296693752481446004  -7670413923544302630        8891365258715654442                       -2486069982777384744  -7210322708539680434              http://www.openbel.org/bel/namespace/selventa-legacy-chemicals              http://www.openbel.org/vocabulary/prefix                          schem                   http://www.w3.org/2001/XMLSchema#string            
4562283096969546622  -8485103775036161392        8891365258715654442                       327606950770410263  -7210322708539680434              http://www.openbel.org/bel/namespace/selventa-legacy-diseases              http://www.openbel.org/vocabulary/prefix                          sdis                    http://www.w3.org/2001/XMLSchema#string            
4895500147765907541  -4514441565986994500        8891365258715654442                       -6637659743822861254  -7210322708539680434              http://www.openbel.org/bel/namespace/mesh-cellular-structures              http://www.openbel.org/vocabulary/prefix                          meshcs                  http://www.w3.org/2001/XMLSchema#string            
5097380505216658639  -2727350442066289402        8891365258715654442                       -4363043793032171563  -7210322708539680434              http://www.openbel.org/bel/namespace/disease-ontology              http://www.openbel.org/vocabulary/prefix                          do                      http://www.w3.org/2001/XMLSchema#string            
6511820928570329606  -7393013952352333055        8891365258715654442                       -6955547283323735094  -7210322708539680434              http://www.openbel.org/bel/namespace/uberon                     http://www.openbel.org/vocabulary/prefix                          uberon                  http://www.w3.org/2001/XMLSchema#string            
6820393681347544038  8696709812581015502        8891365258715654442                       -3555706574775279679  -7210322708539680434              http://www.openbel.org/bel/namespace/hgnc-human-genes              http://www.openbel.org/vocabulary/prefix                          hgnc                    http://www.w3.org/2001/XMLSchema#string            
7302589939682261954  -8870919588248040035        8891365258715654442                       3393709359063564125  -7210322708539680434              http://www.openbel.org/bel/namespace/selventa-protein-families              http://www.openbel.org/vocabulary/prefix                          sfam                    http://www.w3.org/2001/XMLSchema#string            
7821956787822654574  5400458648806173970        8891365258715654442                       8932767905229499789  -7210322708539680434              http://www.openbel.org/bel/namespace/mesh-chemicals              http://www.openbel.org/vocabulary/prefix                          meshc                   http://www.w3.org/2001/XMLSchema#string            
Run Time: real 51.818 user 27.939997 sys 23.779998
```

Any thoughts on the full table scan of the triple_relations table?

**Comment by mro** [comment] 2015-10-24 08:13
yes, but that's an unrealistic query, because the lookup queries of librdf.sqlite operate on hashes only, not strings.

`triples` actually is a view and I have no idea how the sqlite queries and indexes play with views. And there is (intentionally) no index to lookup the string in https://github.com/mro/librdf.sqlite/blob/master/schema_mig_to_1.sql#L43

**Comment by abargnesi** [comment] 2015-10-26 01:50
Ok, that query was just created by me because I couldn't get at the actual query being made when I issued at subject URI basic-graph-pattern (i.e. DESCRIBE URI).

Now I have enabled trace and profile. My experiment was captured in the following gist: https://gist.github.com/abargnesi/345814e9fc650d0d521b

The results of the experiment seem to suggest that the `IS NULL` checks on the hashed URI columns causes a table scan on `triple_relations`. For example my DESCRIBE query above yields the following query:

```sql
SELECT
 -- all *_id (hashes):
  id
  ,s_uri_id
  ,s_blank_id
  ,p_uri_id
  ,o_uri_id
  ,o_blank_id
  ,o_lit_id
  ,o_datatype_id
  ,c_uri_id
 -- all values:
  ,s_uri
  ,s_blank
  ,p_uri
  ,o_uri
  ,o_blank
  ,o_text
  ,o_language
  ,o_datatype
  ,c_uri
FROM triples
WHERE
 -- subject
    ((2665414293436938691   IS NULL) OR (s_uri_id   = 2665414293436938691))
AND ((NULL IS NULL) OR (s_blank_id = NULL))
AND ((NULL   IS NULL) OR (p_uri_id   = NULL))
 -- object
AND ((NULL   IS NULL) OR (o_uri_id   = NULL))
AND ((NULL IS NULL) OR (o_blank_id = NULL))
AND ((NULL   IS NULL) OR (o_lit_id   = NULL))
 -- context node
AND ((NULL   IS NULL) OR (c_uri_id   = NULL))
```

If I remove the `(2665414293436938691   IS NULL)` clause at the front of the where clause then my query goes from 3 seconds to 2 millisconds. Three orders of magnitude difference.

However, doing that will cause basic-graph-patterns that query on a NULL s_uri to not function.

I understand the improvements using a single prepared query, but the table scan shouldn't be necessary. Any ideas come to mind?

If it helps I have a 20 million triple SQLite database (2.7 Gb) that I could send to you. It is open data that I can share.

**Comment by abargnesi** [comment] 2015-10-26 02:00
Actually if you don't mind creating the database yourself you can download the nquads file here:

http://build.openbel.org/browse/OR-INFER/latestSuccessful/artifact/shared/Inferred-namespace-rdf-%28nquads%29/namespaces-inferred.nq.bz2

It contains about 20 million triples and took a couple of hours to insert using `librdf_model_add_statements`.

**Comment by mro** [comment] 2015-10-26 08:35
having time for an in-depth look may take me until Nov 2nd, but:

> the `IS NULL` checks

hngrr. `NULL` and indexes. Surprised that the mentioned check should cause a problem - I expected the column definition to be the cause. IMO https://www.sqlite.org/optoverview.html#idxexamp promises index usage in our case. I don't remember why I chose the semantically correct `NULL` over a `0` (as used in the C code). However a 1e3 speedup is extremely tempting and would make me reconsider the tradeoff against semantic correctness and referential integrity.

> If it helps I have a 20 million triple SQLite database (2.7 Gb) that I could send to you. It is open data that I can share.

Yes, a download link to a sqlite DB file would be helpful.

> My loader code without journaling is here: https://gist.github.com/abargnesi/8402baf1a019a2179e70

the gist uses stock `sqlite` storage where it should use as described at https://github.com/mro/librdf.sqlite#usage, so the timing should be ~100x faster. Can you confirm? (An additional 1000x speedup would still be awesome.)

P.S.: There are different things to try (which require both SQL and C changes):

- abolish `NULL`, use `0` instead but keep referential integrity (and add `0` entries to the `_uri` tables),
- abolish `NULL`, use `0` and break referential integrity,

**Comment by abargnesi** [comment] 2015-10-26 12:06
> IMO https://www.sqlite.org/optoverview.html#idxexamp promises index usage in our case.

The last section seems to indicate that a logical OR may cause a full table scan.

```
 For the index above and WHERE clause like this:

      ... WHERE a=5 OR b IN (1,2,3) OR c NOT NULL OR d='hello'

The index is not usable because the WHERE clause terms are connected by OR instead of AND. This query would result in a full table scan. However, if three additional indices where added that contained columns b, c, and d as their left-most columns, then the OR-clause optimization might apply. 
```

> Yes, a download link to a sqlite DB file would be helpful.

I will get you a link to the database tonight (by 19:00 EDT / 23:00 UTC).

> your gist uses stock sqlite storage where it should use as described at https://github.com/mro/librdf.sqlite#usage, so the timing should be ~100x faster. Can you confirm? (An additional 1000x speedup would still be awesome.)

> See my patched loader.c at https://gist.github.com/mro/8800fab9ef4f38a4ec4e

I see the same differences in load timing between storages. My loader was using librdf with your storage backend replacing the stock sqlite one. More comments and results documented in:

https://gist.github.com/mro/8800fab9ef4f38a4ec4e#gistcomment-1604834

----

I will experiment further with the SQL. Can you give me pointers on where to replace `NULL` with `0`? Where would I insert a `0` for the `*_uris` tables?

**Comment by mro** [comment] 2015-10-26 13:30
hm. The fact that

    select * from triples where 2665414293436938691 IS NULL OR s_uri_id = 2665414293436938691

and

    select * from triples where 0=1 OR s_uri_id = 2665414293436938691

doesn't leverage the index while

    select * from triples where s_uri_id = 2665414293436938691

does, makes my trick of using boolean algebra and a builtin select statement (to avoid generating the SQL per query) not so smart any more. `NULL` seems not the issue here. I guess once the SQL is generated per query, then the indexes are back in the game. I have to think of a way how to do this without excessive string (re-)allocations. https://github.com/mro/librdf.sqlite/blob/9c46881/rdf_storage_sqlite_mro.c#L1231 and below.

**Comment by abargnesi** [comment] 2015-10-26 13:49
Great point. I agree that constant, prepared SQL strings are a benefit worth preserving.

You should be able to allocate a fixed number of SQL queries and choose which to execute based on the query pattern.

For example, give a query on subject URI we might choose to execute:

```sql
SELECT
  -- all *_id (hashes):
  id
  ,s_uri_id
  ,s_blank_id
  ,p_uri_id
  ,o_uri_id
  ,o_blank_id
  ,o_lit_id
  ,o_datatype_id
  ,c_uri_id
  -- all values:
  ,s_uri
  ,s_blank
  ,p_uri
  ,o_uri
  ,o_blank
  ,o_text
  ,o_language
  ,o_datatype
  ,c_uri
FROM triples
WHERE
  -- subject
  (s_uri_id   = :s_uri_id)
  -- predicate
  AND ((:p_uri_id   IS NULL) OR (p_uri_id   = :p_uri_id))
  -- object
  AND ((:o_uri_id   IS NULL) OR (o_uri_id   = :o_uri_id))
  AND ((:o_blank_id IS NULL) OR (o_blank_id = :o_blank_id))
  AND ((:o_lit_id   IS NULL) OR (o_lit_id   = :o_lit_id))
  -- context node
  AND ((:c_uri_id   IS NULL) OR (c_uri_id   = :c_uri_id))
```

For a query on subject and predicate URI the query executed is:

```sql
SELECT
  -- all *_id (hashes):
  id
  ,s_uri_id
  ,s_blank_id
  ,p_uri_id
  ,o_uri_id
  ,o_blank_id
  ,o_lit_id
  ,o_datatype_id
  ,c_uri_id
  -- all values:
  ,s_uri
  ,s_blank
  ,p_uri
  ,o_uri
  ,o_blank
  ,o_text
  ,o_language
  ,o_datatype
  ,c_uri
FROM triples
WHERE
  -- subject
  (s_uri_id = :s_uri_id)
  -- predicate
  AND (p_uri_id = :p_uri_id)
  -- object
  AND ((:o_uri_id   IS NULL) OR (o_uri_id   = :o_uri_id))
  AND ((:o_blank_id IS NULL) OR (o_blank_id = :o_blank_id))
  AND ((:o_lit_id   IS NULL) OR (o_lit_id   = :o_lit_id))
  -- context node
  AND ((:c_uri_id   IS NULL) OR (c_uri_id   = :c_uri_id))
```

By my count this would require 36 SQL strings.

**Comment by mro** [comment] 2015-10-26 20:04
have a look at the branch https://github.com/mro/librdf.sqlite/tree/feature/issue10 - I'm interested if it works properly and how the numbers are for your huge import.

**Comment by rtravis** [comment] 2015-10-26 21:03
I reviewed the last commit in the 'issue10' branch and on first sight it seems to be correct. My first impression was that you should be adding records with ID 0 to the *_uri tables, but then I realized that adding into 'triples' suffices because of the 'triples_insert' trigger takes care of that. The only side effect is the creation of an all zeros record in the triple_relations table.

Your solution to optimize searches (drop nulls) is more elegant than creating many different prepared statements for different cases, the approach I took in my - work in progress - [librdf.firebird](https://github.com/rtravis/librdf.firebird/) currently only for inserting triples.

**Comment by mro** [comment] 2015-10-26 21:48
if we concentrate on 'full triples' - not sparse filter queries - it's 6 queries called in high frequency when adding triples (plus language and datatype). Preparing them seems reasonable. Have to think of how to organize them.

But: I have no idea of how big the boost might be.

**Comment by mro** [comment] 2015-10-27 13:42
after some more thought I'm sure: the above tuning considerations may speed up retrieval, but are not related to inserts and therefore not related to this issue

The `SELECT` statement isn't ever called by `loader.c`. What's called, however, is the `INSERT` but I didn't manage to get a query plan for that. And I can't read the vm instructions, they don't make sense to me.

So unless you guys have an idea, this looks like a `wont fix`to me.

**Comment by abargnesi** [comment] 2015-10-28 01:46
:+1:

The performance is great for the insert. 20 million triples takes about 40 minutes.

The issue is with query performance as you have pointed out. I will experiment starting from your changes in the feature branch.

Should I create a new issue?

**Comment by mro** [comment] 2015-10-28 12:25
ic, yes, new issue. follow up at #11

**Closed by mro** 2015-10-28 12:25 UTC
Labels: enhancement, help wanted, wontfix
